artifacts_root: artifacts

data_ingestion:

  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/vignesh2914/Datasets/raw/refs/heads/main/Rotten_Tomatoes_Movies3.xls.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


